config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get 'rank' => 'alchools#rank'
  root 'homes#top'
  get 'home/about' => 'homes#about',as:'about'
  resources :alchools do
    resources :alcool_comments,only: [:destroy, :create]
    resource :favorites,only: [:destroy, :create]
  end
 end

app/models/alchool.rb
class Alchool < ApplicationRecord
 belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :alcool_comments, dependent: :destroy
 has_many :alchool_genres
 has_many :genres, through: :alchool_genres

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

  def self.search_for(content, method)
   if method == 'perfect'
     Alchool.where(title: content)
   elsif method == 'forward'
     Alchool.where('title LIKE ?', content + '%')
   elsif method == 'backward'
     Alchool.where('title LIKE ?', '%' + content)
   else
    Alchool.where('title LIKE ?', '%' + content + '%')
   end
  end

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/models/alchool_genre.rb
class AlchoolGenre < ApplicationRecord
      belongs_to :alchool
      belongs_to :genre
end

app/models/alcool_comment.rb
class AlcoolComment < ApplicationRecord
  belongs_to :user
  belongs_to :alchool, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :alchool
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :alchool_genres
  has_many :alchools, through: :alchool_genres
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :alchools
  has_many :favorites, dependent: :destroy
  has_many :alcool_comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower


  attachment :profile_image, destroy: false

  validates :introduction, length: {maximum: 50}

def follow(user_id)
  relationships.create(followed_id: user_id)
end

def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
end

def following?(user)
  followings.include?(user)
end
end

app/controllers/alchools_controller.rb
class AlchoolsController < ApplicationController
  before_action :authenticate_user!

  def show
    @alchool = Alchool.find(params[:id])
    @alchool_new = Alchool.new
    @alcool_comment = AlcoolComment.new
    @alcool_comments = AlcoolComment.all
  end

  def index
    @alchools = Alchool.all
    @alchool_new = Alchool.new
    @all_ranks = Alchool.find(Favorite.group(:alchool_id).order('count(alchool_id) desc').limit(3).pluck(:alchool_id))
  end

  def create
    @alchool = Alchool.new(alchool_params)
    @alchool.user_id = current_user.id
    if @alchool.save
      redirect_to alchools_path(@alchool), notice: "You have created book successfully."
    else
      @alchools = Alchool.all
      render 'index'
    end
  end

  def edit
   @alchool = Alchool.find(params[:id])
  end

  def update
    @alchool = Alchool.find(params[:id])
    if @alchool.update(alchool_params)
      redirect_to alchool_path(@alchool), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @alchool = Alchool.find(params[:id])
    @alchool.destroy
    redirect_to alchools_path, notice: "successfully delete book!"
  end

  def rank
    @all_ranks = Alchool.find(Favorite.group(:alchool_id).order('count(alchool_id) desc').limit(3).pluck(:alchool_id))
  end

  private

  def alchool_params
    params.require(:alchool).permit(:title, :body, genre_ids: [])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    alchool = Alchool.find(params[:alchool_id])
    favorite = current_user.favorites.new(alchool_id: alchool.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    alchool = Alchool.find(params[:alchool_id])
    favorite = current_user.favorites.find_by(alchool_id: alchool.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

 def index
  @genre = Genre.new
  @genres = Genre.all
 end

 def create
   @genre = Genre.new(genre_params)
   @genre.save
 end

  def edit
  @genre = Genre.find(params[:id])
  end

  def update
   @genre = Genre.find(params[:id])
   @genre.update(genre_params)
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  def rank
  　@all_ranks = Alchool.find(Favorite.group(:alchool_id).order('count(alchool_id) desc').limit(3).pluck(:alchool_id))
    @alchools = Alchool.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @alchools = @user.alchools
    @alchool = Alchool.new
    @users = User.all
    @all_ranks = Alchool.find(Favorite.group(:alchool_id).order('count(alchool_id) desc').limit(3).pluck(:alchool_id))
  end

  def index
    @users = User.all
    @alchool = Alchool.new
    @all_ranks = Alchool.find(Favorite.group(:alchool_id).order('count(alchool_id) desc').limit(3).pluck(:alchool_id))
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path(@user), notice: "You have updated user successfully."
    else
      render "show"
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/alchool_comments_helper.rb
module AlchoolCommentsHelper
end

app/helpers/alchools_helper.rb
module AlchoolsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/alchools/_favorite.html.erb
    <% if alchool.favorited_by?(current_user) %>
    <p>
    <%= link_to alchool_favorites_path(alchool), method: :delete do %>
        ♥<%= alchool.favorites.count %> いいね
    <% end %>
    </p>
    <% else %>
    <p>
    <%= link_to alchool_favorites_path(alchool), method: :post do %>
        ♡<%= alchool.favorites.count %> いいね
    <% end %>
    </p>
  <% end %>

app/views/alchools/_form.html.erb
<%= form_with model:alchool,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control alchool_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control alchool_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
  <div class="form-group">
    <%= f.label :genre, 'ジャンル' %>
    <%= f.collection_check_boxes(:genre_ids,Genre.all,:id,:name) do |genre| %>
     <%= genre.label do %>
      <%= genre.check_box %>
      <%= genre.tbin/rails cext %>
     <% end %>
     <% end %>
  </div>
<% end %>

app/views/alchools/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% alchools.each do |alchool| %>
      <tr>
        <td><%= link_to user_path(alchool.user) do %>
          <%= attachment_image_tag(alchool.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %>
          <% end %>
        </td>
        <td><%= link_to alchool.title, alchool_path(alchool), class: "alchool_#{alchool.id}" %></td>
        <td><%= alchool.body %></td>
        <td><% if alchool.favorited_by?(current_user) %>
          <p>
            <%= link_to alchool_favorites_path(alchool), method: :delete do %>
            ♥<%= alchool.favorites.count %> いいね
            <% end %>
          </p>
          <% else %>
          <p>
            <%= link_to alchool_favorites_path(alchool), method: :post do %>
            ♡<%= alchool.favorites.count %> いいね
            <% end %>
          </p>
        <% end %>
       </td>
       <td>
        <% alchool.genres.each do |genre| %>
          <%= genre.name %>
        <% end %>
       </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/alchools/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>投稿編集</h1>
    	<%= render 'layouts/errors', obj: @alchool%>
  		<%= render 'form', alchool: @alchool %>
  		<%= link_to 'Show', alchool_path(@alchool), class: "alchool_#{@alchool.id}" %> |
  		<%= link_to 'Back', alchools_path, class: "back" %>
  </div>
</div>

app/views/alchools/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
     <% if @alchool_new.errors.any? %>
      <dv id="error_explanation">
        <h3><%= @alchool_new.errors.count %>error prohibited this obj from being saved:</h3>
        <ul>
          <% @alchool_new.errors.full_messages.each do |message| %>
            <li><%= message %></li>
         <% end %>
        </ul>
      </div>
   <% end %>
    <div class='col-md-3'>
      <h2>ユーザーインフォ</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">新規投稿</h2>
      <%= render 'form', alchool: @alchool_new %>
    </div>
    <div class='col-md-6 offset-md-1'>
      <h2>alchools</h2>
      <%= render 'index', alchools: @alchools,alchool: @alchool%>
    </div>
    <div clas='col-md-3'>
    <table class='table table-hover table-inverse'>
      <h2>ランキング</h2>
      <thead>
        <tr>
          <th>ランキング</th>
          <th>タイトル</th>
        </tr>
      </thead>
    <tbody>
      <% @all_ranks.each.with_index(1) do |alchool,i| %>
      <tr>
        <td>第<%= i %>位</td>
        <td><%=alchool.title%></td>
      <% end %>
      </tr>
    </tbody>
    </table>
    </div>
</div>

app/views/alchools/rank.html.erb
<% @all_ranks.each.with_index(1) do |alchool,i| %>
 第<%= i %>位
 <%=alchool.title%>
<% end %>

app/views/alchools/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>ユーザーインフォ</h2>
      <%= render 'users/info', user: @alchool.user %>
      <h2 class="mt-3">投稿</h2>
      <%= render 'form', alchool: @alchool %>
    </div>
    <div class='col-md-6 offset-md-1'>
  		<h2>投稿詳細</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@alchool.user) do %>
            <%= attachment_image_tag(@alchool.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %><br>
            <%= @alchool.user.name %>
            <% end %>
          </td>
          <td><%= link_to @alchool.title, alchools_path(@alchool) %></td>
          <td><%= @alchool.body %></td>
          <td><%= link_to 'Edit', edit_alchool_path(@alchool), class: "btn btn-sm btn-success edit_alchool_#{@alchool.id}" %></td>
          <td><%= link_to 'Destroy', alchool_path(@alchool), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_alchool_#{@alchool.id}"%></td>
        </tr>
      </table>
            <table>
              <tr>
              <%= form_with(model:[@alchool, @alcool_comment], local: true) do |f| %>
              <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
              <%= f.submit "送信" %>
              <% end %>
              <% @alcool_comments.each do |alcool_comment| %>
              <td><%= attachment_image_tag(alcool_comment.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></td>
              <td><%= alcool_comment.user.name %></td>
              <td><%= alcool_comment.comment %></td>

              <% end %>
              </tr>
            </table>
    </div>
  </div>
</div>

app/views/favorites/_favorite.html.erb
 <% if @alchool.favorited_by?(current_user) %>
    <p>
    <%= link_to alchool_favorites_path(@alchool), method: :delete do %>
        ♥<%= @alchool.favorites.count %> いいね
    <% end %>
    </p>
    <% else %>
    <p>
    <%= link_to alchool_favorites_path(@alchool), method: :post do %>
        ♡<%= @alchool.favorites.count %> いいね
    <% end %>
    </p>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
        <td>
          <% if current_user.following?(user) %>
            <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
              <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
        <tr>
          <td>follows: <%= user.followings.count %></td>
          <td>followers: <%= user.followers.count %></td>
        </tr>
  </tr>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>ユーザーインフォ</h2>
        <%= render 'info', user: current_user %>
        <h2 class="mt-3">新規投稿</h2>
        <%= render 'alchools/form', alchool: @alchool %>
    </div>
    <div class="col-md-6 offset-md-1">
      <h2>Users</h2>
        <%= render 'index',users: @users %>
    </div>
      <div clas='col-md-3'>
    <table class='table table-hover table-inverse'>
      <h2>ランキング</h2>
      <thead>
        <tr>
          <th>ランキング</th>
          <th>タイトル</th>
        </tr>
      </thead>
    <tbody>
      <% @all_ranks.each.with_index(1) do |alchool,i| %>
      <tr>
        <td>第<%= i %>位</td>
        <td><%=alchool.title%></td>
        <% end %>
      </tr>
    </tbody>
    </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>ユーザーインフォ</h2>
      <%= render 'info', user: @user, users: @users%>
      <h2 class="mt-3">新規投稿</h2>
      <%= render 'alchools/form', alchool: @alchool %>
    </div>
    <div class='col-md-6 offset-md-1'>
      <h2>投稿したお酒たち</h2>
      <%= render 'alchools/index',alchools: @alchools%>
    </div>
    <div clas='col-md-3'>
    <table class='table table-hover table-inverse'>
      <h2>ランキング</h2>
      <thead>
        <tr>
          <th>ランキング</th>
          <th>タイトル</th>
        </tr>
      </thead>
    <tbody>
      <% @all_ranks.each.with_index(1) do |alchool,i| %>
      <tr>
        <td>第<%= i %>位</td>
        <td><%=alchool.title%></td>
        <% end %>
      </tr>
    </tbody>
    </table>
    </div>
  </div>
</div>