config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get 'rank' => 'alchools#rank'
  root 'homes#top'
  get 'home/about' => 'homes#about',as:'about'
  resources :alchools do
    resources :alcool_comments,only: [:destroy, :create]
    resource :favorites,only: [:destroy, :create]
  end
 end

app/models/alchool.rb
class Alchool < ApplicationRecord
 belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :alcool_comments, dependent: :destroy
 has_many :alchool_genres
 has_many :genres, through: :alchool_genres

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

  def self.search_for(content, method)
   if method == 'perfect'
     Alchool.where(title: content)
   elsif method == 'forward'
     Alchool.where('title LIKE ?', content + '%')
   elsif method == 'backward'
     Alchool.where('title LIKE ?', '%' + content)
   else
    Alchool.where('title LIKE ?', '%' + content + '%')
   end
  end

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/models/alchool_genre.rb
class AlchoolGenre < ApplicationRecord
      belongs_to :alchool
      belongs_to :genre
end

app/models/alcool_comment.rb
class AlcoolComment < ApplicationRecord
  belongs_to :user
  belongs_to :alchool, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :alchool
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :alchool_genres
  has_many :alchools, through: :alchool_genres
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :alchools
  has_many :favorites, dependent: :destroy
  has_many :alcool_comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower


  attachment :profile_image, destroy: false

  validates :introduction, length: {maximum: 50}

def follow(user_id)
  relationships.create(followed_id: user_id)
end

def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
end

def following?(user)
  followings.include?(user)
end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

 def index
  @genre = Genre.new
  @genres = Genre.all
 end

 def create
   @genre = Genre.new(genre_params)
   @genre.save
 end

  def edit
  @genre = Genre.find(params[:id])
  end

  def update
   @genre = Genre.find(params[:id])
   @genre.update(genre_params)
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  def rank
  　@all_ranks = Alchool.find(Favorite.group(:alchool_id).order('count(alchool_id) desc').limit(3).pluck(:alchool_id))
    @alchools = Alchool.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @alchools = @user.alchools
    @alchool = Alchool.new
    @users = User.all
    @all_ranks = Alchool.find(Favorite.group(:alchool_id).order('count(alchool_id) desc').limit(3).pluck(:alchool_id))
  end

  def index
    @users = User.all
    @alchool = Alchool.new
    @all_ranks = Alchool.find(Favorite.group(:alchool_id).order('count(alchool_id) desc').limit(3).pluck(:alchool_id))
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path(@user), notice: "You have updated user successfully."
    else
      render "show"
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/alchools_helper.rb
module AlchoolsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SakeEkas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header class="sticky-top">
      <nav class="navbar navbar-expand-md navbar-light bg-light text-black">
        <a class=>
          <%= link_to 'SAKE-EKAS', root_path, data: {"turbolinks" => false}, class: "header-logo"%><i class="fas fa-glass-cheers"></i>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "ホーム", user_path(current_user),class:"nav-item" %>
              </li>
              <li class="nav-item">
                <%= link_to "ユーザー", users_path,class:"nav-item" %>
              </li>
              <li class="nav-item">
                <%= link_to "投稿一覧", alchools_path,class:"nav-item" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path,class:"nav-item" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "トップページ", "/",class: "nav-item" %>
              </li>
              <li class="nav-item">
                <%= link_to "アバウト", about_path, class:"nav-item" %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path,class: "nav-item" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path,class: "nav-item" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>